spring :
  datasource :
    url : jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/dirs
    username : ${DATASOURCE_USER:postgres}
    password : ${DATASOURCE_PASS:postgres}
  flyway:
    baselineOnMigrate: true

server:
  error:
    include-stacktrace : always

driver-class-name : org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
              SQL: TRACE